### ISSUE TITLE
tableview

### ISSUE THREAD

**Issue by ZClee128** [maple1994/WeiboHomePage#1]
数据源不够的时候，点击按钮滑上去顶部会出现bug，回到数据源多的页面头部就多了一大块

**Comment by maple1994** [comment]
的确有这个bug，我还没想过这种情况。我晚点修复好了上传新的版本上来

**Comment by maple1994** [comment]
已修复，增加了一个判断是否滚动到顶部的代理，当滚动顶部时，将所有偏移量置0。可以下载新版本查看

**Comment by ZClee128** [comment]
你提交了吗，我没看到你修改了哪里呀

**Comment by maple1994** [comment]
额，忘记同步到github了。。现在更新了 =。 =

**Comment by ZClee128** [comment]
试过了，你修改的方法还是不行

**Comment by maple1994** [comment]
你的bug是怎么出现的？是固定头部时，点击状态栏滚动到顶部，再切换，之后顶部出现一大片留白？你看我新增的tableViewDidScrollToTop有没调用？

**Comment by ZClee128** [comment]
有qq吗，我好截图给你看看

**Comment by maple1994** [comment]
305554601
